apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::016108180036:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1LJTYKSNYSOT2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::016108180036:role/UdacityFlaskDeployCBKubectlRole
      username: build 
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-26T22:22:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1253"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 41343036-9c5b-4cee-b493-8b63b386d97c
